backend:
  name: git-gateway
  branch: main # Cambia a 'master' si tu rama principal en GitHub se llama master

media_folder: "assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "base_de_datos"
    label: "Base de Datos"
    files:
      - file: "data/noticias.json"
        label: "Lista de Noticias"
        name: "noticias_json"
        fields:
          - label: "Noticias"
            name: ""
            widget: "list"
            summary: "{{fields.id}} - {{fields.title}}"
            fields:
      - { label: "ID de la Nota", name: "id", widget: "string" }      
      - { label: "Título de la Nota", name: "title", widget: "string" }
      - { label: "Subtítulo / Resumen", name: "subtitle", widget: "text", required: false }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { 
          label: "Autor / Redactor", 
          name: "author", 
          widget: "select", 
          default: "Prensa Cafeteando",
          options: [
            "Prensa Cafeteando",
            "Antonio García",
            "Giovanni Garcia",
            "Javier Aguilar",
            "Prensa APREPSAC"
          ] 
        }
      - { 
          label: "Categoría / Tag", 
          name: "tag", 
          widget: "select", 
          options: [
            "OPINIÓN", 
            "NACIONAL", 
            "LOCAL / EMPRESARIAL", 
            "PUEBLA Y DEPORTES", 
            "GASTRONOMÍA Y SALUD"
          ] 
        }
      - { label: "Imagen Destacada", name: "image", widget: "image", required: false }
      - { label: "Documento PDF Adjunto (Ej. Convocatorias)", name: "pdf", widget: "file", required: false }
      - { label: "Fragmento de Audio / Podcast (MP3)", name: "audio", widget: "file", required: false }
      - { label: "Cuerpo de la Nota", name: "body", widget: "markdown" }