backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "base_de_datos"
    label: "📰 Gestión de Noticias"
    files:
      - file: "data/noticias.json"
        label: "Lista General de Noticias"
        name: "noticias_list"
        fields:
          - label: "Publicaciones"
            name: ""
            widget: "list"
            summary: "ID: {{fields.id}} | {{fields.title}}"
            minimize_collapsed: true
            fields:
              - { label: "ID Único de la Nota", name: "id", widget: "number", value_type: "int" }
              - { label: "Título Principal", name: "title", widget: "string" }
              - label: "Categoría / Sección"
                name: "tag"
                widget: "select"
                options:
                  - "GASTRONOMÍA"
                  - "GASTRONOMÍA & REUNIONES"
                  - "GASTRONOMÍA Y SALUD"
                  - "LOCAL / EMPRESARIAL"
                  - "NACIONAL / LOCAL"
                  - "PUEBLA Y DEPORTES"
                  - "NACIONAL / RESUMEN DE PRENSA"
                  - "OPINIÓN"
                default: "GASTRONOMÍA"

              - { label: "Fecha de Publicación", name: "date", widget: "string" }
              - { label: "Autor / Redactor", name: "author", widget: "string", default: "Antonio García" }
              - { label: "Ubicación / Ciudad", name: "location", widget: "string", default: "Puebla, Pue." }
              - { label: "Imagen Destacada", name: "image", widget: "image", required: false }
              - { label: "ID de Video de YouTube (Opcional)", name: "youtube_id", widget: "string", required: false }
              - { label: "Pie de Imagen / Video", name: "caption", widget: "string", required: false }
              - { label: "Introducción / Copete", name: "intro", widget: "text" }
              - { label: "Cuerpo Completo de la Noticia (Acepta HTML)", name: "content", widget: "text" }
              - label: "Recomendaciones Especiales (Opcional)"
                name: "recommendations"
                widget: "list"
                required: false
                field: { label: "Recomendación", widget: "string" }